# Generated by Django 5.0.6 on 2025-06-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lostitem',
            name='date_reported',
        ),
        migrations.RemoveField(
            model_name='lostitem',
            name='item_name',
        ),
        migrations.AddField(
            model_name='lostitem',
            name='date_lost',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lostitem',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
    ]
